### ISSUE TITLE
Example using received audio data?

### ISSUE THREAD

**Issue by asg0451** [serenity-rs/songbird#100]
I'm hacking on this example (https://github.com/serenity-rs/songbird/blob/current/examples/serenity/voice_receive/src/main.rs), and I can receive and buffer voice audio, but I can't figure out what format it's in or how to use it.

I've got some of these https://serenity-rs.github.io/songbird/current/songbird/events/context_data/struct.VoiceData.html#structfield.audio but what *is* this? How can I turn this into, say, a .wav file? 

I've been banging my head on this one for a couple hours so any help would be greatly appreciated!

**Comment by FelixMcFelix** [comment]
This should be documented somewhere, you're right!

Each event contains up to 20ms of mono 16-bit PCM audio from a single user at 48kHZ -- each `i16` is a sample.

If you want to make a wave file per user:
* You need to emit a suitable wav header.
  * This is [documented here](http://soundfile.sapp.org/doc/WaveFormat/), or you can look into a Rust library for this, e.g. [wav](https://crates.io/crates/wav).
* The `i16` data should just go into the data subchunk without any issues, just be careful around endianness. However, you need to pad silent regions with zeroes by yourself, because clients don't send packets when they aren't talking. Mostly. 🙂 

If you want to combine them all:
* As above, except you need to need to add all packets which arrive in the same 20ms window together.
 * Mixing two audio packets is simply summing over all input measurements.
 * Take care not to overflow/clip the additions -- you might need to do volume reduction.
* Some other users have tackled this for e.g., bridging [Discord<->TS3](https://github.com/0xpr03/voice-bridge).

**Comment by asg0451** [comment]
wow, thanks! this is incredibly helpful. 
re your second bullet, can you elaborate on being careful around endianness? This PCM data is big-endian, right? i think i saw that implied somewhere in the discord docs, such as they are.

**Comment by FelixMcFelix** [comment]
The PCM data *you* receive is in the endianness of your machine; you just
need to be careful saving it to disk (i.e., "RIFF vs "RIFX" determines this
in the WAV header, and I think the `wav` library just handles this for you).

**Comment by asg0451** [comment]
Ah gotcha. Thanks again, you have saved me hours of struggling with opus and discord documentation. If you want, I could do a quick PR to add basically what you said to the bit of documentation I linked initially.

**Comment by FelixMcFelix** [comment]
Thanks; that would be very helpful if you could do so.
