### ISSUE TITLE
Is there a way to get a mutable reference to a track in a queue?

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#3]
I need to be able to edit a track in a queue, is there a way to grab a mutable reference to a track in a queue?  Or a way to grab a mutable reference to the internal VecDeque?

**Comment by FelixMcFelix** [comment]
It depends on what you mean, or what you need.

[`Track`](https://serenity-rs.github.io/songbird/current/songbird/tracks/struct.Track.html)s, once active, cannot be directly mutated again because they are now owned by the driver. They are now controlled by sending commands over a [`TrackHandle`](https://serenity-rs.github.io/songbird/current/songbird/tracks/struct.TrackHandle.html).

Currently, you can clone a track's `handle` before passing it into the queue (i.e., create it using [this method](https://serenity-rs.github.io/songbird/current/songbird/tracks/fn.create_player.html)). I might add a function to return a read-only view of the inner queue, or at least the current track's handle. I'm reluctant to add mutable access, since tracks need specific event handlers---or else the queue would be fragile. I have some ideas on how to make this work (i.e., allow reordering, but force addition via type-safe means).

I have some other queue changes in mind too. I'll keep ergonomic ideas/questions in mind!

**Comment by peppizza** [comment]
I definitely think there should be a function to return a handle to a track, along with functions to remove a track in a queue at a specific index if that is possible
