### ISSUE TITLE
TrackEvent::End not firing when calling queue.stop() when there is more then one song in the queue

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#30]
I have a global track end event registered to remove some data from a hashmap, however calling queue.stop() only fires the event if there is one song in the queue, otherwise it won't fire for any of the tracks.

**Comment by FelixMcFelix** [comment]
Hi, are you still getting this issue? I just tested clearing out an entire queue on `examples/serenity/voice_events_queue`: the list of all tracks killed in the same tick is as long as it should be (i.e., a 3-song queue -> ~stop -> the event contains 3 `(&state, &handle)` pairs). This is by design to minimise the amount of events which need to be fired—especially when there could be multiple track end handlers!

**Comment by peppizza** [comment]
I no longer use the builtin queue, (too much memory usage using full tracks), so I can not confirm if it still exists

**Comment by FelixMcFelix** [comment]
Closing for now, then.
