### ISSUE TITLE
Don't return Err result when ytdl produces a warning

### ISSUE THREAD

**Issue by alecks** [serenity-rs/songbird#37]
Youtube-dl warning messages are written to stderr, causing `songbird::ytdl` to fail if one is produced. Since it's _usually_ not fatal, I think that whether or not it should continue should be configurable.

**Comment by FelixMcFelix** [comment]
Thanks for raising this. Could you give some indication of the sort of warning/error that can pop up, or an example URL that's triggering failure?

Feel free to PR a new variant function which forcibly ignores errors, or that silences warning from `youtube-dl`. 😄

**Comment by alecks** [comment]
`WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.` is pretty common, but it's possible (though not the best idea) to ignore it. Would it be okay to use `tracing::warn` for only warning messages in the original function?

**Comment by FelixMcFelix** [comment]
It should be, if you can find a way to reasonably/safely separate them out from any actual errors. Keep in mind that the track metadata is *also* output on stderr, and is siphoned off accordingly so that we can get away with fewer calls to `youtube-dl` (and fewer network requests).

Otherwise, please add `--no-warnings` to the default argument list.

**Comment by vilgotf** [comment]
I encountered this recently trying to play https://opus-codec.org/static/examples/samples/speech_orig.wav. yt-dl can download it, but songbird says that the warning "Falling back on generic information extractor" is an error thus failing to play
