### ISSUE TITLE
Stack overflow when quitting the runtime

### ISSUE THREAD

**Issue by 0xpr03** [serenity-rs/songbird#88]
Finally found the time to verify this. Use the `voice` example from songbird with serenity and change the client start to
```rust
tokio::spawn(async move {
    let _ = client.start().await.map_err(|why| println!("Client ended: {:?}", why));
});

tokio::signal::ctrl_c().await;
println!("Received Ctrl-C, shutting down.");
```

After voice is connected (~join) one tokio-runtime-worker will overflow its stack upon Ctrl+C to exit the runtime, apparently by indefinitely recursing `songbird::driver::Driver::restart_inner()` -> `mute` -> `send`.

Stack trace is [here](https://gist.github.com/0xpr03/0771cd7ec1f37140725ee38d64e9ca36), as rusts internal backtrace will not work any more.

Crashing code example is [here](https://github.com/0xpr03/songbird_repro/blob/aac5054251b925e07dddbf1bb4c0ae51c1356b32/examples/serenity/voice/src/main.rs#L66-L71)

**Comment by FelixMcFelix** [comment]
The issue is in the `impl Drop` for `Driver`, which tries to kill the driver thread but apparently goes off the rails. I think all that needs to be removed is the `self.leave()`---sending the poison value should actually just kill the threads as required.

(Weird sense of déja vu with this---I actually thought this had been fixed before such that I knew where the issue was, but there's no commit/PR there.)
