### ISSUE TITLE
Can't seek lazy Restartable near beginning

### ISSUE THREAD

**Issue by evanc577** [serenity-rs/songbird#97]
**Songbird version:** 0.2.0

**Rust version:** rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Serenity version:** 0.10.9

**Description:**

When using `Restartable::ytdl()` with `lazy = true`, attempting to seek a track before it starts playing will return `SeekUnsupported`. This is despite the track reporting that it is seekable. Also, if an event near triggered near the beginning of the track tries to seek the track, it will fail silently. 

**Steps to reproduce:**

Create a lazy Restartable and try to seek it.

```rust
let source = Restartable::ytdl(url.to_owned(), true).await.unwrap();
let (mut track, track_handle) = songbird::tracks::create_player(source.into());

// Try to seek
dbg!(track_handle.is_seekable());
track.seek_time(Duration::from_secs(10)).unwrap();
```

Seek fails even though the track reports that it is seekable.

```
[src/main.rs:218] track_handle.is_seekable() = true
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SeekUnsupported', src/main.rs:219:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Try to add an seeking event at the start of the track.

```rust
let source = Restartable::ytdl(url.to_owned(), true).await.unwrap();
let (mut track, track_handle) = songbird::tracks::create_player(source.into());

// Add event
track_handle
    .add_event(
        Event::Delayed(Duration::from_millis(5)),
        Seeker {
            seek_to: Duration::from_secs(20),
        },
    )
    .unwrap();

// Play track
handler.play(track);
```

```rust
struct Seeker {
    seek_to: Duration,
}

#[async_trait]
impl VoiceEventHandler for Seeker {
    async fn act(&self, ctx: &EventContext<'_>) -> Option<Event> {
        if let EventContext::Track(&[(_, track)]) = ctx {
            track.seek_time(self.seek_to).unwrap();
            event!(Level::INFO, "Seek to {:?}", self.seek_to);
        }
        None
    }
}
```

The event seeks without errors, but actual audio output is not seeked.

```
[2021-09-28T22:42:26Z INFO  discord_bot] Seek to 20s
```

**Comment by FelixMcFelix** [comment]
Thanks. It looks as though all seek errors are being folded into `Unsupported` for some reason, changing this might help identify what's *actually* happening. It should be trying to make the source ready before it begins a seek, which can fail accordingly: `"Cannot safely call seek until provided an async context handle."`. I'd made `Reader::prep_with_handle` private since I expected only the mixer to make use of it -- and you need this passed in to initialise during a seek! This is probably reasonable to fix (either make public, or have logic to check for being in an async context).

As for why that 20s seek by the mixer is failing, I'm not too sure right now from just looking at code, might need to poke at that one for a while...

**Comment by FelixMcFelix** [comment]
Closing due to age and as we have significantly reworked how seeking and recreation of sources work internally.
